### ISSUE TITLE
ImportError: No module named 'tdo'

### ISSUE THREAD

**Issue by tocsinDE** [tdolist/tdo#19]
Installing tdo worked. But calling tdo resulted in this:

```
Traceback (most recent call last):
  File "/usr/bin/tdo", line 9, in <module>
    load_entry_point('tdo==0.7', 'console_scripts', 'tdo')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'tdo'
```

**Comment by tocsinDE** [comment]
Okay, it was partly my fault.
Installing pip helped (sigh..), but running setup.py needs root.
